name: "dradis-ce-production"

services:
  web:
    # image: dradis/dradis-ce:latest
    build:
      context: .
      platforms:
        - linux/amd64
    volumes:
      # Persist the database
      - dradis-ce-storage:/app/storage
    ports:
      - 443:443
      - 80:80
    environment:
      # Set domain from ENV var so thruster can handle let's encrypt certificates
      - TLS_DOMAIN=${TLS_DOMAIN}
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost/up"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  dradis-ce-storage:
